# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pageMain(object):
    def setupUi(self, pageMain):
        pageMain.setObjectName("pageMain")
        pageMain.resize(960, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pageMain.sizePolicy().hasHeightForWidth())
        pageMain.setSizePolicy(sizePolicy)
        pageMain.setMinimumSize(QtCore.QSize(960, 720))
        pageMain.setMaximumSize(QtCore.QSize(960, 720))
        self.centralwidget = QtWidgets.QWidget(pageMain)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 10, 931, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_left = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_left.setObjectName("table_left")
        self.table_left.setColumnCount(0)
        self.table_left.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.table_left)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.table_right = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_right.setObjectName("table_right")
        self.table_right.setColumnCount(0)
        self.table_right.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.table_right)
        self.horizontalLayout_2.setStretch(0, 20)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 20)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_map = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.btn_map.setFont(font)
        self.btn_map.setObjectName("btn_map")
        self.horizontalLayout.addWidget(self.btn_map)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_n = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_n.setFont(font)
        self.label_n.setObjectName("label_n")
        self.horizontalLayout.addWidget(self.label_n)
        self.btn_next = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.btn_next.setFont(font)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        pageMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pageMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        pageMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pageMain)
        self.statusbar.setObjectName("statusbar")
        pageMain.setStatusBar(self.statusbar)

        self.retranslateUi(pageMain)
        QtCore.QMetaObject.connectSlotsByName(pageMain)

    def retranslateUi(self, pageMain):
        _translate = QtCore.QCoreApplication.translate
        pageMain.setWindowTitle(_translate("pageMain", "Solution of Maze"))
        self.label.setText(_translate("pageMain", "Solution of Maze"))
        self.btn_map.setText(_translate("pageMain", "Generate Map"))
        self.label_2.setText(_translate("pageMain", "Current N ="))
        self.label_n.setText(_translate("pageMain", "?"))
        self.btn_next.setText(_translate("pageMain", "Next Step"))
